# Generated by Django 6.0.2 on 2026-05-31 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coches', to='app_gestion_taller.cliente')),
            ],
            options={
                'verbose_name': 'Coche',
                'verbose_name_plural': 'Coches',
                'ordering': ['matricula'],
            },
        ),
        migrations.CreateModel(
            name='CocheServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coche_servicios', to='app_gestion_taller.coche')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coche_servicios', to='app_gestion_taller.servicio')),
            ],
            options={
                'verbose_name': 'Servicio de coche',
                'verbose_name_plural': 'Servicios de coches',
                'unique_together': {('coche', 'servicio')},
            },
        ),
    ]
